In [ ]:
storageAccountName = 'equitymarketstorage'
storageAccountAccessKey = '32Q+pSDygN/vBS/+2OPfjXJrW9+T4gogsOJY3mEob/GON/Hls27FX1ZaxbBxEjsmA+/+XJn1AXkFj2dUSrOeWA=='
blobContainerName = 'firstcontainer'


if not any(mount.mountPoint == '/mnt/FileStore/MountFolder/' for mount in dbutils.fs.mounts()):
  try:
    dbutils.fs.mount(
    source = "wasbs://{}@{}.blob.core.windows.net".format(blobContainerName, storageAccountName),
    mount_point = "/mnt/FileStore/MountFolder/",
    extra_configs = {'fs.azure.account.key.' + storageAccountName + '.blob.core.windows.net': storageAccountAccessKey}
  )
  except Exception as e:
    print("already mounted. Try to unmount first")

In [ ]:
import requests
import pandas as pd
import concurrent.futures

group_names = ["DP02", "DP03", "DP04", "DP05"]


def census_request():
    HOST = "https://api.census.gov/data"
    dataset = "acs/acs1/profile"
    return HOST, dataset


def get_predicates(group_name):
    predicates = {}
    get_vars = "group({})".format(group_name)
    predicates["get"] = get_vars
    #get_vars = ["DP02_" + str(i+1).zfill(4) + "E" for i in range(154)]
    #get_vars = "group(DP02)"
    #predicates["for"] = "metropolitan%20statistical%20area/micropolitan%20statistical%20area:*"
    predicates["for"] = "county:*"
    predicates["key"] = "e61340309f1ac39404000c3efba3d6921c359b66"
    return predicates


def download_census_tables(group_name):
    for year in range(2011, 2020):
        HOST, dataset = census_request()
        predicates = get_predicates(group_name)
        base_url = "/".join([HOST, str(year), dataset])
        result = requests.get(base_url, params=predicates)
        df = pd.DataFrame(columns=result.json()[0], data=result.json()[1:])
        df["year"] = year
        print(df.head(3))
        fname = "{}.csv".format(year)
        df.to_csv(fname)
    
  """    
download_census_tables(group_names[0])
download_census_tables(group_names[1])
download_census_tables(group_names[2])
download_census_tables(group_names[3])
"""

with concurrent.futures.ThreadPoolExecutor() as executor:
    print("Getting Data...")
    executor.map(download_census_tables, group_names)

In [ ]:
From above we can see we have None valued columns which we can drop later on. Also we have -99999999 on some rows. We can replace them with average value of the column.

In [ ]:
import requests
import pandas as pd
import concurrent.futures

group_names = ["DP02", "DP03", "DP04", "DP05"]


def census_request():
    HOST = "https://api.census.gov/data"
    dataset = "acs/acs1/profile"
    return HOST, dataset


def get_predicates(group_name):
    predicates = {}
    get_vars = "group({})".format(group_name)
    predicates["get"] = get_vars
    #get_vars = ["DP02_" + str(i+1).zfill(4) + "E" for i in range(154)]
    #get_vars = "group(DP02)"
    #predicates["for"] = "metropolitan%20statistical%20area/micropolitan%20statistical%20area:*"
    predicates["for"] = "state:*"
    predicates["key"] = "e61340309f1ac39404000c3efba3d6921c359b66"
    return predicates


def download_census_tables(group_name):
    for year in range(2011, 2020):
        HOST, dataset = census_request()
        predicates = get_predicates(group_name)
        base_url = "/".join([HOST, str(year), dataset])
        result = requests.get(base_url, params=predicates)
        df = pd.DataFrame(columns=result.json()[0], data=result.json()[1:])
        df["year"] = year
        print(df.head(3))
        fname = "{}.csv".format(year)
        df.to_csv(fname)
    
"""    
download_census_tables(group_names[0])
download_census_tables(group_names[1])
download_census_tables(group_names[2])
download_census_tables(group_names[3])
"""

with concurrent.futures.ThreadPoolExecutor() as executor:
    print("Getting Data...")
    executor.map(download_census_tables, group_names)

In [ ]:
Here I decide to get state level data instead of county level. 
Here we see spme columns has -55555555 and -88888888. I might drop them r replace them with 0 or average value. Also, None  values needs to be replaced with 0.

In [ ]:
There are some useful annotation values to work with datasets. 

Estimate Value	Annotation Value	Meaning
-666666666	-	The estimate could not be computed because there were an insufficient number of sample observations. For a ratio of medians estimate, one or both of the median estimates falls in the lowest interval or     highest interval of an open-ended distribution.
-999999999	N	The estimate or margin of error cannot be displayed because there were an insufficient number of sample cases in the selected geographic area.
-888888888	(X)	The estimate or margin of error is not applicable or not available.
Varies	median-	The median falls in the lowest interval of an open-ended distribution (for example "2,500-")
Varies	median+	The median falls in the highest interval of an open-ended distribution (for example "250,000+").
-222222222	**	The margin of error could not be computed because there were an insufficient number of sample observations.
-333333333	***	The margin of error could not be computed because the median falls in the lowest interval or highest interval of an open-ended distribution.
-555555555	*****	A margin of error is not appropriate because the corresponding estimate is controlled to an independent population or housing estimate. Effectively, the corresponding estimate has no sampling error and the margin of error may be treated as zero.
*	N/A	An * indicates that the estimate is significantly different (at a 90% confidence level) than the estimate from the most current year. A "c" indicates the estimates for that year and the current year are both controlled; a statistical test is not appropriate.
null	null	A null value in the estimate means there is no data available for the requested geography.